apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vproapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regax: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: vprofile.yasithuvanpriya.xyz
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: vproapp-service
              port:
                number: 8080